### PR TITLE
Server validates entries in the background

### LINKED ISSUE #70: Automated STARTTLS validation
The scanner should run daily validation checks against:
1. Queued policies
     - If a queued domain/policy fails validation, it gets marked as StateFailed and an email should notify them at the end of the waiting period that a) their TLS policy couldn't be loaded onto the list, and b) how, why, and when their policy failed validation.

2. Policies on the list
    - If a policy on the list fails validation, an email should notify them immediately that a) something is misconfigured and could be affecting deliverability, and b) how, why, and when their policy failed validation.

This is currently being done slightly manually by me & a cronjob.

### PR DESCRIPTION
**Pull request by sydneyli**
fixes #70, new & updated version of #72 
let's have the server do this so i can stop doing this manually \o/

### CODE REVIEW

File: policy/policy.go [hunk 1]
```diff
@@ -63,6 +63,33 @@ type UpdatedList struct {
...
+	defer l.mu.RUnlock()
+	domains := []string{}
+	for domain := range l.Policies {
+		domains = append(domains, domain)
+	}
+	return domains, nil
+}
+
+// HostnamesForDomain [interface Validator] retrieves the hostname policy for
+// a particular domain.
```
Comment (vbrown608) [inline policy/policy.go]: The comment about what interface this satisfies is really helpful. I think I will adopt that practice...

**Comment by vbrown608** [comment]
Looks good to me! I really like how flexible the validator is. It's nice that everything is already set up for concurrency! 

I moved the result body to Sentry's extra context field. It's a little weird to access it in their go implementation, had to add a Class method to DomainResult ¯\_(ツ)_/¯

This way it will have some helpful JSON structure in the UI and all the events of this type will be grouped under a single message.
